/* tslint:disable */
/* eslint-disable */
/**
 * PP Label ML backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Model
 */
export interface Model {
  /**
   *
   * @type {string}
   * @memberof Model
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof Model
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof Model
   */
  taskCategories?: string;
  /**
   *
   * @type {boolean}
   * @memberof Model
   */
  interactive?: boolean;
  /**
   *
   * @type {Array<string>}
   * @memberof Model
   */
  labelNames?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof Model
   */
  languages?: Array<string>;
}

/**
 * Check if a given object implements the Model interface.
 */
export function instanceOfModel(value: object): value is Model {
  return true;
}

export function ModelFromJSON(json: any): Model {
  return ModelFromJSONTyped(json, false);
}

export function ModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'] == null ? undefined : json['name'],
    description: json['description'] == null ? undefined : json['description'],
    taskCategories: json['task_categories'] == null ? undefined : json['task_categories'],
    interactive: json['interactive'] == null ? undefined : json['interactive'],
    labelNames: json['label_names'] == null ? undefined : json['label_names'],
    languages: json['languages'] == null ? undefined : json['languages'],
  };
}

export function ModelToJSON(value?: Model | null): any {
  if (value == null) {
    return value;
  }
  return {
    name: value['name'],
    description: value['description'],
    task_categories: value['taskCategories'],
    interactive: value['interactive'],
    label_names: value['labelNames'],
    languages: value['languages'],
  };
}
