/* tslint:disable */
/* eslint-disable */
/**
 * PP Label ML backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PredictRequestOther } from './PredictRequestOther';
import {
  PredictRequestOtherFromJSON,
  PredictRequestOtherFromJSONTyped,
  PredictRequestOtherToJSON,
} from './PredictRequestOther';

/**
 *
 * @export
 * @interface PredictRequest
 */
export interface PredictRequest {
  /**
   *
   * @type {string}
   * @memberof PredictRequest
   */
  img: string;
  /**
   *
   * @type {string}
   * @memberof PredictRequest
   */
  format: string;
  /**
   *
   * @type {object}
   * @memberof PredictRequest
   */
  piggyback?: object;
  /**
   *
   * @type {PredictRequestOther}
   * @memberof PredictRequest
   */
  other?: PredictRequestOther;
}

/**
 * Check if a given object implements the PredictRequest interface.
 */
export function instanceOfPredictRequest(value: object): value is PredictRequest {
  if (!('img' in value) || value['img'] === undefined) return false;
  if (!('format' in value) || value['format'] === undefined) return false;
  return true;
}

export function PredictRequestFromJSON(json: any): PredictRequest {
  return PredictRequestFromJSONTyped(json, false);
}

export function PredictRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PredictRequest {
  if (json == null) {
    return json;
  }
  return {
    img: json['img'],
    format: json['format'],
    piggyback: json['piggyback'] == null ? undefined : json['piggyback'],
    other: json['other'] == null ? undefined : PredictRequestOtherFromJSON(json['other']),
  };
}

export function PredictRequestToJSON(value?: PredictRequest | null): any {
  if (value == null) {
    return value;
  }
  return {
    img: value['img'],
    format: value['format'],
    piggyback: value['piggyback'],
    other: PredictRequestOtherToJSON(value['other']),
  };
}
