/* tslint:disable */
/* eslint-disable */
/**
 * PP Label ML backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PredictRequestOther
 */
export interface PredictRequestOther {
  /**
   *
   * @type {Array<any>}
   * @memberof PredictRequestOther
   */
  clicks?: Array<any>;
}

/**
 * Check if a given object implements the PredictRequestOther interface.
 */
export function instanceOfPredictRequestOther(value: object): value is PredictRequestOther {
  return true;
}

export function PredictRequestOtherFromJSON(json: any): PredictRequestOther {
  return PredictRequestOtherFromJSONTyped(json, false);
}

export function PredictRequestOtherFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PredictRequestOther {
  if (json == null) {
    return json;
  }
  return {
    clicks: json['clicks'] == null ? undefined : json['clicks'],
  };
}

export function PredictRequestOtherToJSON(value?: PredictRequestOther | null): any {
  if (value == null) {
    return value;
  }
  return {
    clicks: value['clicks'],
  };
}
