/* tslint:disable */
/* eslint-disable */
/**
 * PaddleLabel API Specs
 * Web backend APIs for PaddleLabel
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AddTagRequest
 */
export interface AddTagRequest {
  /**
   *
   * @type {number}
   * @memberof AddTagRequest
   */
  tagId?: number;
}

/**
 * Check if a given object implements the AddTagRequest interface.
 */
export function instanceOfAddTagRequest(value: object): value is AddTagRequest {
  return true;
}

export function AddTagRequestFromJSON(json: any): AddTagRequest {
  return AddTagRequestFromJSONTyped(json, false);
}

export function AddTagRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddTagRequest {
  if (json == null) {
    return json;
  }
  return {
    tagId: json['tag_id'] == null ? undefined : json['tag_id'],
  };
}

export function AddTagRequestToJSON(value?: AddTagRequest | null): any {
  if (value == null) {
    return value;
  }
  return {
    tag_id: value['tagId'],
  };
}
