/* tslint:disable */
/* eslint-disable */
/**
 * PaddleLabel API Specs
 * Web backend APIs for PaddleLabel
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateCacheRequest
 */
export interface CreateCacheRequest {
  /**
   *
   * @type {string}
   * @memberof CreateCacheRequest
   */
  content?: string;
}

/**
 * Check if a given object implements the CreateCacheRequest interface.
 */
export function instanceOfCreateCacheRequest(value: object): value is CreateCacheRequest {
  return true;
}

export function CreateCacheRequestFromJSON(json: any): CreateCacheRequest {
  return CreateCacheRequestFromJSONTyped(json, false);
}

export function CreateCacheRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateCacheRequest {
  if (json == null) {
    return json;
  }
  return {
    content: json['content'] == null ? undefined : json['content'],
  };
}

export function CreateCacheRequestToJSON(value?: CreateCacheRequest | null): any {
  if (value == null) {
    return value;
  }
  return {
    content: value['content'],
  };
}
