/* tslint:disable */
/* eslint-disable */
/**
 * PaddleLabel API Specs
 * Web backend APIs for PaddleLabel
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ExportDatasetRequest
 */
export interface ExportDatasetRequest {
  /**
   *
   * @type {string}
   * @memberof ExportDatasetRequest
   */
  exportDir: string;
  /**
   *
   * @type {string}
   * @memberof ExportDatasetRequest
   */
  exportFormat?: string;
  /**
   *
   * @type {string}
   * @memberof ExportDatasetRequest
   */
  segMaskType?: string;
}

/**
 * Check if a given object implements the ExportDatasetRequest interface.
 */
export function instanceOfExportDatasetRequest(value: object): value is ExportDatasetRequest {
  if (!('exportDir' in value) || value['exportDir'] === undefined) return false;
  return true;
}

export function ExportDatasetRequestFromJSON(json: any): ExportDatasetRequest {
  return ExportDatasetRequestFromJSONTyped(json, false);
}

export function ExportDatasetRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ExportDatasetRequest {
  if (json == null) {
    return json;
  }
  return {
    exportDir: json['export_dir'],
    exportFormat: json['export_format'] == null ? undefined : json['export_format'],
    segMaskType: json['seg_mask_type'] == null ? undefined : json['seg_mask_type'],
  };
}

export function ExportDatasetRequestToJSON(value?: ExportDatasetRequest | null): any {
  if (value == null) {
    return value;
  }
  return {
    export_dir: value['exportDir'],
    export_format: value['exportFormat'],
    seg_mask_type: value['segMaskType'],
  };
}
