/* tslint:disable */
/* eslint-disable */
/**
 * PaddleLabel API Specs
 * Web backend APIs for PaddleLabel
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GetFoldersRequest
 */
export interface GetFoldersRequest {
  /**
   *
   * @type {string}
   * @memberof GetFoldersRequest
   */
  path?: string;
}

/**
 * Check if a given object implements the GetFoldersRequest interface.
 */
export function instanceOfGetFoldersRequest(value: object): value is GetFoldersRequest {
  return true;
}

export function GetFoldersRequestFromJSON(json: any): GetFoldersRequest {
  return GetFoldersRequestFromJSONTyped(json, false);
}

export function GetFoldersRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetFoldersRequest {
  if (json == null) {
    return json;
  }
  return {
    path: json['path'] == null ? undefined : json['path'],
  };
}

export function GetFoldersRequestToJSON(value?: GetFoldersRequest | null): any {
  if (value == null) {
    return value;
  }
  return {
    path: value['path'],
  };
}
