/* tslint:disable */
/* eslint-disable */
/**
 * PaddleLabel API Specs
 * Web backend APIs for PaddleLabel
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GetProgress200Response
 */
export interface GetProgress200Response {
  /**
   *
   * @type {number}
   * @memberof GetProgress200Response
   */
  finished?: number;
  /**
   *
   * @type {number}
   * @memberof GetProgress200Response
   */
  total?: number;
}

/**
 * Check if a given object implements the GetProgress200Response interface.
 */
export function instanceOfGetProgress200Response(value: object): value is GetProgress200Response {
  return true;
}

export function GetProgress200ResponseFromJSON(json: any): GetProgress200Response {
  return GetProgress200ResponseFromJSONTyped(json, false);
}

export function GetProgress200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetProgress200Response {
  if (json == null) {
    return json;
  }
  return {
    finished: json['finished'] == null ? undefined : json['finished'],
    total: json['total'] == null ? undefined : json['total'],
  };
}

export function GetProgress200ResponseToJSON(value?: GetProgress200Response | null): any {
  if (value == null) {
    return value;
  }
  return {
    finished: value['finished'],
    total: value['total'],
  };
}
