/* tslint:disable */
/* eslint-disable */
/**
 * PaddleLabel API Specs
 * Web backend APIs for PaddleLabel
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Label
 */
export interface Label {
  /**
   *
   * @type {number}
   * @memberof Label
   */
  labelId?: number;
  /**
   *
   * @type {number}
   * @memberof Label
   */
  projectId?: number;
  /**
   *
   * @type {string}
   * @memberof Label
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof Label
   */
  color?: string;
  /**
   *
   * @type {string}
   * @memberof Label
   */
  comment?: string;
  /**
   *
   * @type {string}
   * @memberof Label
   */
  readonly created?: string;
  /**
   *
   * @type {string}
   * @memberof Label
   */
  readonly modified?: string;
  /**
   *
   * @type {number}
   * @memberof Label
   */
  superCategoryId?: number;
}

/**
 * Check if a given object implements the Label interface.
 */
export function instanceOfLabel(value: object): value is Label {
  if (!('name' in value) || value['name'] === undefined) return false;
  return true;
}

export function LabelFromJSON(json: any): Label {
  return LabelFromJSONTyped(json, false);
}

export function LabelFromJSONTyped(json: any, ignoreDiscriminator: boolean): Label {
  if (json == null) {
    return json;
  }
  return {
    labelId: json['label_id'] == null ? undefined : json['label_id'],
    projectId: json['project_id'] == null ? undefined : json['project_id'],
    name: json['name'],
    color: json['color'] == null ? undefined : json['color'],
    comment: json['comment'] == null ? undefined : json['comment'],
    created: json['created'] == null ? undefined : json['created'],
    modified: json['modified'] == null ? undefined : json['modified'],
    superCategoryId: json['super_category_id'] == null ? undefined : json['super_category_id'],
  };
}

export function LabelToJSON(value?: Omit<Label, 'created' | 'modified'> | null): any {
  if (value == null) {
    return value;
  }
  return {
    label_id: value['labelId'],
    project_id: value['projectId'],
    name: value['name'],
    color: value['color'],
    comment: value['comment'],
    super_category_id: value['superCategoryId'],
  };
}
