/* tslint:disable */
/* eslint-disable */
/**
 * PaddleLabel API Specs
 * Web backend APIs for PaddleLabel
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface LoadSampleRequest
 */
export interface LoadSampleRequest {
  /**
   *
   * @type {number}
   * @memberof LoadSampleRequest
   */
  taskCategoryId?: number;
}

/**
 * Check if a given object implements the LoadSampleRequest interface.
 */
export function instanceOfLoadSampleRequest(value: object): value is LoadSampleRequest {
  return true;
}

export function LoadSampleRequestFromJSON(json: any): LoadSampleRequest {
  return LoadSampleRequestFromJSONTyped(json, false);
}

export function LoadSampleRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LoadSampleRequest {
  if (json == null) {
    return json;
  }
  return {
    taskCategoryId: json['task_category_id'] == null ? undefined : json['task_category_id'],
  };
}

export function LoadSampleRequestToJSON(value?: LoadSampleRequest | null): any {
  if (value == null) {
    return value;
  }
  return {
    task_category_id: value['taskCategoryId'],
  };
}
