/* tslint:disable */
/* eslint-disable */
/**
 * PaddleLabel API Specs
 * Web backend APIs for PaddleLabel
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface LoadSample200Response
 */
export interface LoadSample200Response {
  /**
   *
   * @type {number}
   * @memberof LoadSample200Response
   */
  projectId?: number;
}

/**
 * Check if a given object implements the LoadSample200Response interface.
 */
export function instanceOfLoadSample200Response(value: object): value is LoadSample200Response {
  return true;
}

export function LoadSample200ResponseFromJSON(json: any): LoadSample200Response {
  return LoadSample200ResponseFromJSONTyped(json, false);
}

export function LoadSample200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LoadSample200Response {
  if (json == null) {
    return json;
  }
  return {
    projectId: json['project_id'] == null ? undefined : json['project_id'],
  };
}

export function LoadSample200ResponseToJSON(value?: LoadSample200Response | null): any {
  if (value == null) {
    return value;
  }
  return {
    project_id: value['projectId'],
  };
}
