/* tslint:disable */
/* eslint-disable */
/**
 * PaddleLabel API Specs
 * Web backend APIs for PaddleLabel
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PaddlelabelApiControllerUserLoginRequest
 */
export interface PaddlelabelApiControllerUserLoginRequest {
  /**
   *
   * @type {string}
   * @memberof PaddlelabelApiControllerUserLoginRequest
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof PaddlelabelApiControllerUserLoginRequest
   */
  password: string;
}

/**
 * Check if a given object implements the PaddlelabelApiControllerUserLoginRequest interface.
 */
export function instanceOfPaddlelabelApiControllerUserLoginRequest(
  value: object,
): value is PaddlelabelApiControllerUserLoginRequest {
  if (!('username' in value) || value['username'] === undefined) return false;
  if (!('password' in value) || value['password'] === undefined) return false;
  return true;
}

export function PaddlelabelApiControllerUserLoginRequestFromJSON(
  json: any,
): PaddlelabelApiControllerUserLoginRequest {
  return PaddlelabelApiControllerUserLoginRequestFromJSONTyped(json, false);
}

export function PaddlelabelApiControllerUserLoginRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PaddlelabelApiControllerUserLoginRequest {
  if (json == null) {
    return json;
  }
  return {
    username: json['username'],
    password: json['password'],
  };
}

export function PaddlelabelApiControllerUserLoginRequestToJSON(
  value?: PaddlelabelApiControllerUserLoginRequest | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    username: value['username'],
    password: value['password'],
  };
}
