/* tslint:disable */
/* eslint-disable */
/**
 * PaddleLabel API Specs
 * Web backend APIs for PaddleLabel
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Points2polygonRequest
 */
export interface Points2polygonRequest {
  /**
   *
   * @type {string}
   * @memberof Points2polygonRequest
   */
  points?: string;
}

/**
 * Check if a given object implements the Points2polygonRequest interface.
 */
export function instanceOfPoints2polygonRequest(value: object): value is Points2polygonRequest {
  return true;
}

export function Points2polygonRequestFromJSON(json: any): Points2polygonRequest {
  return Points2polygonRequestFromJSONTyped(json, false);
}

export function Points2polygonRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Points2polygonRequest {
  if (json == null) {
    return json;
  }
  return {
    points: json['points'] == null ? undefined : json['points'],
  };
}

export function Points2polygonRequestToJSON(value?: Points2polygonRequest | null): any {
  if (value == null) {
    return value;
  }
  return {
    points: value['points'],
  };
}
