/* tslint:disable */
/* eslint-disable */
/**
 * PaddleLabel API Specs
 * Web backend APIs for PaddleLabel
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Polygon2pointsRequest
 */
export interface Polygon2pointsRequest {
  /**
   *
   * @type {string}
   * @memberof Polygon2pointsRequest
   */
  polygon?: string;
}

/**
 * Check if a given object implements the Polygon2pointsRequest interface.
 */
export function instanceOfPolygon2pointsRequest(value: object): value is Polygon2pointsRequest {
  return true;
}

export function Polygon2pointsRequestFromJSON(json: any): Polygon2pointsRequest {
  return Polygon2pointsRequestFromJSONTyped(json, false);
}

export function Polygon2pointsRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Polygon2pointsRequest {
  if (json == null) {
    return json;
  }
  return {
    polygon: json['polygon'] == null ? undefined : json['polygon'],
  };
}

export function Polygon2pointsRequestToJSON(value?: Polygon2pointsRequest | null): any {
  if (value == null) {
    return value;
  }
  return {
    polygon: value['polygon'],
  };
}
