/* tslint:disable */
/* eslint-disable */
/**
 * PaddleLabel API Specs
 * Web backend APIs for PaddleLabel
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectOtherSettingsLabelMappingInner } from './ProjectOtherSettingsLabelMappingInner';
import {
  ProjectOtherSettingsLabelMappingInnerFromJSON,
  ProjectOtherSettingsLabelMappingInnerFromJSONTyped,
  ProjectOtherSettingsLabelMappingInnerToJSON,
} from './ProjectOtherSettingsLabelMappingInner';
import type { ProjectOtherSettingsModelSettingsValue } from './ProjectOtherSettingsModelSettingsValue';
import {
  ProjectOtherSettingsModelSettingsValueFromJSON,
  ProjectOtherSettingsModelSettingsValueFromJSONTyped,
  ProjectOtherSettingsModelSettingsValueToJSON,
} from './ProjectOtherSettingsModelSettingsValue';

/**
 *
 * @export
 * @interface ProjectOtherSettings
 */
export interface ProjectOtherSettings {
  /**
   * ML后端地址，一般是 http://localhost:1234
   * @type {string}
   * @memberof ProjectOtherSettings
   */
  mlBackendUrl?: string;
  /**
   *
   * @type {string}
   * @memberof ProjectOtherSettings
   * @deprecated
   */
  perviousModel?: string;
  /**
   *
   * @type {object}
   * @memberof ProjectOtherSettings
   * @deprecated
   */
  models?: object;
  /**
   * 正在使用的模型名称
   * @type {string}
   * @memberof ProjectOtherSettings
   */
  modelName?: string;
  /**
   * 标签对应关系
   * @type {Array<ProjectOtherSettingsLabelMappingInner>}
   * @memberof ProjectOtherSettings
   */
  labelMapping?: Array<ProjectOtherSettingsLabelMappingInner>;
  /**
   *
   * @type {{ [key: string]: ProjectOtherSettingsModelSettingsValue; }}
   * @memberof ProjectOtherSettings
   */
  modelSettings?: { [key: string]: ProjectOtherSettingsModelSettingsValue };
  /**
   *
   * @type {string}
   * @memberof ProjectOtherSettings
   */
  modelFilePath?: string;
  /**
   *
   * @type {string}
   * @memberof ProjectOtherSettings
   */
  paramFilePath?: string;
  /**
   *
   * @type {string}
   * @memberof ProjectOtherSettings
   */
  lang?: string;
  /**
   *
   * @type {boolean}
   * @memberof ProjectOtherSettings
   */
  isSample?: boolean;
  /**
   *
   * @type {string}
   * @memberof ProjectOtherSettings
   */
  clasSubCatg?: string;
}

/**
 * Check if a given object implements the ProjectOtherSettings interface.
 */
export function instanceOfProjectOtherSettings(value: object): value is ProjectOtherSettings {
  return true;
}

export function ProjectOtherSettingsFromJSON(json: any): ProjectOtherSettings {
  return ProjectOtherSettingsFromJSONTyped(json, false);
}

export function ProjectOtherSettingsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProjectOtherSettings {
  if (json == null) {
    return json;
  }
  return {
    mlBackendUrl: json['mlBackendUrl'] == null ? undefined : json['mlBackendUrl'],
    perviousModel: json['perviousModel'] == null ? undefined : json['perviousModel'],
    models: json['models'] == null ? undefined : json['models'],
    modelName: json['modelName'] == null ? undefined : json['modelName'],
    labelMapping:
      json['labelMapping'] == null
        ? undefined
        : (json['labelMapping'] as Array<any>).map(ProjectOtherSettingsLabelMappingInnerFromJSON),
    modelSettings:
      json['modelSettings'] == null
        ? undefined
        : mapValues(json['modelSettings'], ProjectOtherSettingsModelSettingsValueFromJSON),
    modelFilePath: json['modelFilePath'] == null ? undefined : json['modelFilePath'],
    paramFilePath: json['paramFilePath'] == null ? undefined : json['paramFilePath'],
    lang: json['lang'] == null ? undefined : json['lang'],
    isSample: json['isSample'] == null ? undefined : json['isSample'],
    clasSubCatg: json['clasSubCatg'] == null ? undefined : json['clasSubCatg'],
  };
}

export function ProjectOtherSettingsToJSON(value?: ProjectOtherSettings | null): any {
  if (value == null) {
    return value;
  }
  return {
    mlBackendUrl: value['mlBackendUrl'],
    perviousModel: value['perviousModel'],
    models: value['models'],
    modelName: value['modelName'],
    labelMapping:
      value['labelMapping'] == null
        ? undefined
        : (value['labelMapping'] as Array<any>).map(ProjectOtherSettingsLabelMappingInnerToJSON),
    modelSettings:
      value['modelSettings'] == null
        ? undefined
        : mapValues(value['modelSettings'], ProjectOtherSettingsModelSettingsValueToJSON),
    modelFilePath: value['modelFilePath'],
    paramFilePath: value['paramFilePath'],
    lang: value['lang'],
    isSample: value['isSample'],
    clasSubCatg: value['clasSubCatg'],
  };
}
