/* tslint:disable */
/* eslint-disable */
/**
 * PaddleLabel API Specs
 * Web backend APIs for PaddleLabel
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskCategory } from './TaskCategory';
import {
  TaskCategoryFromJSON,
  TaskCategoryFromJSONTyped,
  TaskCategoryToJSON,
} from './TaskCategory';
import type { Label } from './Label';
import { LabelFromJSON, LabelFromJSONTyped, LabelToJSON } from './Label';
import type { ProjectOtherSettings } from './ProjectOtherSettings';
import {
  ProjectOtherSettingsFromJSON,
  ProjectOtherSettingsFromJSONTyped,
  ProjectOtherSettingsToJSON,
} from './ProjectOtherSettings';

/**
 * project info and settings
 * @export
 * @interface Project
 */
export interface Project {
  /**
   * project表的主键，从1开始
   * @type {number}
   * @memberof Project
   */
  readonly projectId?: number;
  /**
   * 项目名字
   * @type {string}
   * @memberof Project
   */
  name?: string;
  /**
   * Optional project description
   * @type {string}
   * @memberof Project
   */
  description?: string;
  /**
   * Absolute directory path where all the data file is stored
   * @type {string}
   * @memberof Project
   */
  dataDir?: string;
  /**
   * Top level annotation task category, see TODO for int <-> category map
   * @type {number}
   * @memberof Project
   */
  taskCategoryId?: number;
  /**
   *
   * @type {TaskCategory}
   * @memberof Project
   */
  taskCategory?: TaskCategory;
  /**
   *
   * @type {Array<Label>}
   * @memberof Project
   */
  labels?: Array<Label>;
  /**
   * Project creation timestamp in UTC
   * @type {string}
   * @memberof Project
   */
  readonly created?: string;
  /**
   * Last time the project detail or ANY TASK of the project is modified
   * @type {string}
   * @memberof Project
   */
  readonly modified?: string;
  /**
   * A string that is unique to each project
   * @type {string}
   * @memberof Project
   */
  upid?: string;
  /**
   *
   * @type {ProjectOtherSettings}
   * @memberof Project
   */
  otherSettings?: ProjectOtherSettings;
  /**
   * This property is only used for passing project create/export options around more easilly. It's discarded after the project is created or exported.
   * @type {object}
   * @memberof Project
   */
  allOptions?: object;
}

/**
 * Check if a given object implements the Project interface.
 */
export function instanceOfProject(value: object): value is Project {
  return true;
}

export function ProjectFromJSON(json: any): Project {
  return ProjectFromJSONTyped(json, false);
}

export function ProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): Project {
  if (json == null) {
    return json;
  }
  return {
    projectId: json['project_id'] == null ? undefined : json['project_id'],
    name: json['name'] == null ? undefined : json['name'],
    description: json['description'] == null ? undefined : json['description'],
    dataDir: json['data_dir'] == null ? undefined : json['data_dir'],
    taskCategoryId: json['task_category_id'] == null ? undefined : json['task_category_id'],
    taskCategory:
      json['task_category'] == null ? undefined : TaskCategoryFromJSON(json['task_category']),
    labels: json['labels'] == null ? undefined : (json['labels'] as Array<any>).map(LabelFromJSON),
    created: json['created'] == null ? undefined : json['created'],
    modified: json['modified'] == null ? undefined : json['modified'],
    upid: json['upid'] == null ? undefined : json['upid'],
    otherSettings:
      json['other_settings'] == null
        ? undefined
        : ProjectOtherSettingsFromJSON(json['other_settings']),
    allOptions: json['all_options'] == null ? undefined : json['all_options'],
  };
}

export function ProjectToJSON(
  value?: Omit<Project, 'project_id' | 'created' | 'modified'> | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    name: value['name'],
    description: value['description'],
    data_dir: value['dataDir'],
    task_category_id: value['taskCategoryId'],
    task_category: TaskCategoryToJSON(value['taskCategory']),
    labels: value['labels'] == null ? undefined : (value['labels'] as Array<any>).map(LabelToJSON),
    upid: value['upid'],
    other_settings: ProjectOtherSettingsToJSON(value['otherSettings']),
    all_options: value['allOptions'],
  };
}
