/* tslint:disable */
/* eslint-disable */
/**
 * PaddleLabel API Specs
 * Web backend APIs for PaddleLabel
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SetAllRequest
 */
export interface SetAllRequest {
  /**
   *
   * @type {boolean}
   * @memberof SetAllRequest
   */
  dataPredicted?: boolean;
}

/**
 * Check if a given object implements the SetAllRequest interface.
 */
export function instanceOfSetAllRequest(value: object): value is SetAllRequest {
  return true;
}

export function SetAllRequestFromJSON(json: any): SetAllRequest {
  return SetAllRequestFromJSONTyped(json, false);
}

export function SetAllRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetAllRequest {
  if (json == null) {
    return json;
  }
  return {
    dataPredicted: json['data_predicted'] == null ? undefined : json['data_predicted'],
  };
}

export function SetAllRequestToJSON(value?: SetAllRequest | null): any {
  if (value == null) {
    return value;
  }
  return {
    data_predicted: value['dataPredicted'],
  };
}
