/* tslint:disable */
/* eslint-disable */
/**
 * PaddleLabel API Specs
 * Web backend APIs for PaddleLabel
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SplitDatasetRequest
 */
export interface SplitDatasetRequest {
  /**
   *
   * @type {number}
   * @memberof SplitDatasetRequest
   */
  train?: number;
  /**
   *
   * @type {number}
   * @memberof SplitDatasetRequest
   */
  val?: number;
  /**
   *
   * @type {number}
   * @memberof SplitDatasetRequest
   */
  test?: number;
}

/**
 * Check if a given object implements the SplitDatasetRequest interface.
 */
export function instanceOfSplitDatasetRequest(value: object): value is SplitDatasetRequest {
  return true;
}

export function SplitDatasetRequestFromJSON(json: any): SplitDatasetRequest {
  return SplitDatasetRequestFromJSONTyped(json, false);
}

export function SplitDatasetRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SplitDatasetRequest {
  if (json == null) {
    return json;
  }
  return {
    train: json['train'] == null ? undefined : json['train'],
    val: json['val'] == null ? undefined : json['val'],
    test: json['test'] == null ? undefined : json['test'],
  };
}

export function SplitDatasetRequestToJSON(value?: SplitDatasetRequest | null): any {
  if (value == null) {
    return value;
  }
  return {
    train: value['train'],
    val: value['val'],
    test: value['test'],
  };
}
