/* tslint:disable */
/* eslint-disable */
/**
 * PaddleLabel API Specs
 * Web backend APIs for PaddleLabel
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TagTask
 */
export interface TagTask {
  /**
   *
   * @type {number}
   * @memberof TagTask
   */
  tagTaskId?: number;
  /**
   *
   * @type {number}
   * @memberof TagTask
   */
  projectId?: number;
  /**
   *
   * @type {number}
   * @memberof TagTask
   */
  tagId?: number;
  /**
   *
   * @type {number}
   * @memberof TagTask
   */
  taskId?: number;
}

/**
 * Check if a given object implements the TagTask interface.
 */
export function instanceOfTagTask(value: object): value is TagTask {
  return true;
}

export function TagTaskFromJSON(json: any): TagTask {
  return TagTaskFromJSONTyped(json, false);
}

export function TagTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagTask {
  if (json == null) {
    return json;
  }
  return {
    tagTaskId: json['tag_task_id'] == null ? undefined : json['tag_task_id'],
    projectId: json['project_id'] == null ? undefined : json['project_id'],
    tagId: json['tag_id'] == null ? undefined : json['tag_id'],
    taskId: json['task_id'] == null ? undefined : json['task_id'],
  };
}

export function TagTaskToJSON(value?: TagTask | null): any {
  if (value == null) {
    return value;
  }
  return {
    tag_task_id: value['tagTaskId'],
    project_id: value['projectId'],
    tag_id: value['tagId'],
    task_id: value['taskId'],
  };
}
