/* tslint:disable */
/* eslint-disable */
/**
 * PaddleLabel API Specs
 * Web backend APIs for PaddleLabel
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TaskCategory
 */
export interface TaskCategory {
  /**
   *
   * @type {string}
   * @memberof TaskCategory
   */
  name?: string;
  /**
   *
   * @type {number}
   * @memberof TaskCategory
   */
  taskCategoryId?: number;
  /**
   *
   * @type {string}
   * @memberof TaskCategory
   * @deprecated
   */
  handler?: string;
  /**
   *
   * @type {string}
   * @memberof TaskCategory
   */
  created?: string;
  /**
   *
   * @type {string}
   * @memberof TaskCategory
   */
  modified?: string;
}

/**
 * Check if a given object implements the TaskCategory interface.
 */
export function instanceOfTaskCategory(value: object): value is TaskCategory {
  return true;
}

export function TaskCategoryFromJSON(json: any): TaskCategory {
  return TaskCategoryFromJSONTyped(json, false);
}

export function TaskCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskCategory {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'] == null ? undefined : json['name'],
    taskCategoryId: json['task_category_id'] == null ? undefined : json['task_category_id'],
    handler: json['handler'] == null ? undefined : json['handler'],
    created: json['created'] == null ? undefined : json['created'],
    modified: json['modified'] == null ? undefined : json['modified'],
  };
}

export function TaskCategoryToJSON(value?: TaskCategory | null): any {
  if (value == null) {
    return value;
  }
  return {
    name: value['name'],
    task_category_id: value['taskCategoryId'],
    handler: value['handler'],
    created: value['created'],
    modified: value['modified'],
  };
}
