/* tslint:disable */
/* eslint-disable */
/**
 * PaddleLabel API Specs
 * Web backend APIs for PaddleLabel
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface User
 */
export interface User {
  /**
   *
   * @type {number}
   * @memberof User
   */
  readonly userId?: number;
  /**
   *
   * @type {string}
   * @memberof User
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  password?: string;
  /**
   *
   * @type {number}
   * @memberof User
   */
  roleId?: number;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
  return true;
}

export function UserFromJSON(json: any): User {
  return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
  if (json == null) {
    return json;
  }
  return {
    userId: json['user_id'] == null ? undefined : json['user_id'],
    name: json['name'] == null ? undefined : json['name'],
    email: json['email'] == null ? undefined : json['email'],
    password: json['password'] == null ? undefined : json['password'],
    roleId: json['role_id'] == null ? undefined : json['role_id'],
  };
}

export function UserToJSON(value?: Omit<User, 'user_id'> | null): any {
  if (value == null) {
    return value;
  }
  return {
    name: value['name'],
    email: value['email'],
    password: value['password'],
    role_id: value['roleId'],
  };
}
